[StylePrimary]
H=(20*#Scale#)
InlineSetting=Face | #Font#
InlineSetting2=Weight | 100
InlineSetting3=Size | (14*#Scale#)
InlineSetting4=Color | #FontColor#,255
InlineSetting5=Shadow | 1 | 1 | 1 | 0,0,0,100
AntiAlias=1
StringAlign=LeftCenter

[StyleSecondary]
H=(20*#Scale#)
InlineSetting=Face | #Font#
InlineSetting2=Weight | 100
InlineSetting3=Size | (12*#Scale#)
InlineSetting4=Color | #FontColor#,200
InlineSetting5=Shadow | 1 | 1 | 1 | 0,0,0,100
AntiAlias=1
StringAlign=RightCenter
NumOfDecimals=1
Padding=0,0,(2*#Scale#),0

[StyleValue]
StringAlign=LeftCenter
InlineSetting=Face | #Font#
InlineSetting2=Weight | 100
InlineSetting3=Size | (32*#Scale#)
InlineSetting4=Color | #FontColor#,255
AntiAlias=1
InlineSetting5=Shadow | 1 | 1 | 1 | 0,0,0,100
